[WEB-7296] add getVouchers method to ecom client
serato/sws-php-sdk pull request #70
Opened 2022-06-30 01:58 UTC by luke-wyeth

2022-06-30 02:18 UTC, gabrieljo requested changes
Nice work @luke-wyeth I think you missed unit test for the command `voucherList`

2022-06-30 02:18 UTC, gabrieljo commented on src/Ecom/Command/VoucherList.php
> +            'user_id'       => ['type' => self::ARG_TYPE_INTEGER, 'required' => true]
Too much space.

2022-06-30 02:18 UTC, gabrieljo commented on src/Ecom/EcomClient.php
> +            'GetSubscriptions'         => SubscriptionList::class,
Nice one.

2022-06-30 22:42 UTC, gabrieljo approved these changes
LGTM. Nice work! @luke-wyeth

2022-07-05 00:25 UTC, electric approved these changes
Looks good - nice work @Mike-Serato

2022-07-05 00:38 UTC, merged